### ISSUE TITLE
Logic behind the UsbContext trait

### ISSUE THREAD

**Issue by joelreymont** [a1ien/rusb#181]
Why was it necessary to introduce the UsbContext trait?

I tried to wrap rusb in a simpler library, with a device and open, read, write, close functions. It seems like the UsbContext trait makes it impossible to hide rusb and leaks through.

Am I missing something?

**Comment by a1ien** [comment]
Because in libusb you actually can have many context. You can read more about libusb context here https://libusb.sourceforge.io/api-1.0/libusb_contexts.html
Also if you use not Global context this allow you to ensure that you close all usb handler. Because you must stop all communication before you destroy context.

For you library you can just need to create you own wrapper.
```rust
use std::time::Duration;

use rusb::{DeviceHandle, GlobalContext, UsbContext};

pub struct Device {
    dev: DeviceHandle<GlobalContext>,
}

impl Device {
    pub fn open(vendor_id: u16, product_id: u16) {
        GlobalContext {}.open_device_with_vid_pid(vendor_id, product_id);
    }

    pub fn read(&self, endpoint: u8, buf: &mut [u8], timeout: Duration) -> rusb::Result<usize> {
        self.dev.read_bulk(endpoint, buf, timeout)
    }

    pub fn write(&self, endpoint: u8, buf: &[u8], timeout: Duration) -> rusb::Result<usize> {
        self.dev.write_bulk(endpoint, buf, timeout)
    }
}

```
And you don't need to separate close, because if `DeviceHandle` is dropped it close the device

**Comment by joelreymont** [comment]
Thank you very much!
