### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by justinmoon** [a1ien/rusb#19]
I understand that [libusb offers some Android support](https://github.com/libusb/libusb/tree/master/android).

Has anyone tested this on Android?

**Comment by avantgardnerio** [comment]
It does work, but I've only been able to use it as root from the command line due to permissions issues.

**Comment by otavio** [comment]
Maybe it is due the lack of write permissions to the devices? maybe a rules file for udev might solve it?

**Comment by avantgardnerio** [comment]
Take a look at the ticket I just opened: https://github.com/a1ien/rusb/issues/34 .

I'm not an expert, but to my knowledge, Android doesn't have anything like udev rules because they built a unified permissions model up in JVM land and want to control access there, even if folks like us would rather be working down in JNI. If you know more I'd be open to hearing...

**Comment by avantgardnerio** [comment]
> I understand that [libusb offers some Android support](https://github.com/libusb/libusb/tree/master/android).
> 
> Has anyone tested this on Android?

@justinmoon there's now a working example here: https://github.com/a1ien/rusb/pull/39/files#diff-e1c008c9f9a3bbe1af5114cf1a2433ddR64

**Comment by brandonros** [comment]
@avantgardnerio I know this is 3 years later but... I wonder if something broke?

In your Rust JNI library code you have

```rust
#[no_mangle]
pub unsafe extern fn Java_com_github_a1ien_rusb_example_rustandroidusb_MainActivity_listAndroid(
    env: JNIEnv,
    _obj: JObject,
    fds: jintArray,
) -> jstring {
    android_logger::init_once(Config::default().with_min_level(Level::Debug));

    let mut str = "".to_owned();
    let len = env.get_array_length(fds).unwrap();
    let mut ints = vec![0i32; len as usize];
    env.get_int_array_region(fds, 0, &mut ints);
    str.push_str(format!("Listing Android devices:\n").as_str());
    for fd in ints {
        let ctx: *mut libusb_context = GlobalContext::default().as_raw();
        let fd = fd as isize as *mut i32;
        let mut handle: *mut libusb_device_handle = null_mut();
        let res = libusb_wrap_sys_device(ctx, fd, &mut handle);
        if res != 0 {
            error!("libusb error code: {}", res);
            continue;
        }
        let ptr = std::ptr::NonNull::new(handle).unwrap();
        let mut handle = DeviceHandle::from_libusb(GlobalContext::default(), ptr);
        let device = handle.device();
        let device_desc = match device.device_descriptor() {
            Ok(d) => d,
            Err(_) => continue,
        };
        str.push_str(format!(
            "Bus {:03} Device {:03} ID {:04x}:{:04x}\n",
            device.bus_number(),
            device.address(),
            device_desc.vendor_id(),
            device_desc.product_id()
        ).as_str());
    }
    **env.new_string(str).unwrap()
}
```

That would cause `libusb_init()` to be called through https://github.com/a1ien/rusb/blob/master/src/context.rs#L215-L217 because of

```rust
impl UsbContext for GlobalContext {
    fn as_raw(&self) -> *mut libusb_context {
```

`libusb_init` is known to return `LIBUSB_ERROR_IO` on Android: https://github.com/libusb/libusb/issues/941

Not sure the recommendations here are out of date. I'll try `open_device_with_fd`

**Comment by avantgardnerio** [comment]
@brandonros I'm sorry, it has been a few years, I've changed companies, and don't have access to the equipment I used to test this on. I'm glad you figured it out though!
