### ISSUE TITLE
Implementation help

### ISSUE THREAD

**Issue by rogerioadris** [a1ien/rusb#49]
> Sorry I don't know English, I'm using the translator.

I'm migrating a Python project to Rust and I'm looking for a replacement for the ["python-usbtmc"](https://pypi.org/project/python-usbtmc/) library and found this one.

My need is to write and read data from a Tektronix oscilloscope, writing I was able to do it but I was unable to read the data.

Any tips on how to do it?

**Comment by tecywiz121** [comment]
I'm not the maintainer, but it would probably be useful to see your code, if possible.

**Comment by rogerioadris** [comment]
My code is [here](https://github.com/rogerioadris/rust-usbtmc)

I implemented only part of writing, [here](https://github.com/rogerioadris/rust-usbtmc/blob/32e6816c18647022fc2e00544464fba0634b0933/src/instrument.rs#L118)

**Comment by a1ien** [comment]
I think the problem is that the exchange protocol is not fully implemented. For example, if you look at the code in python, you can see that at the time of opening, the `self.clear()` function is also called, which makes several ctrl_trasfer https://github.com/python-ivi/python-usbtmc/blob/d9bfb20b2ef002da787adb6b093e1679705c00e2/usbtmc/usbtmc.py#L828

Also I can suggest run wireshark and compare what request you send and what send "python-usbtmc"

**Comment by rogerioadris** [comment]
Does this wireshark work usb too ?

I'm not using a network, but a usb cable connected to a raspberry.

**Comment by a1ien** [comment]
> Does this wireshark work usb too ?

Yes https://wiki.wireshark.org/CaptureSetup/USB
