### ISSUE TITLE
Unsoundness with !Send and Hotplug

### ISSUE THREAD

**Issue by tecywiz121** [a1ien/rusb#50]
If the `Hotplug` passed to `register_callback` is `!Send`, but `UsbContext::handle_events` is called from another thread, the `Hotplug` is sent to that thread.

The following code demonstrates what I believe is the unsound behaviour:

```rust
use rusb::{Device, Error, GlobalContext, Hotplug, UsbContext};

use std::rc::Rc;

#[derive(Default)]
struct Unsend(Rc<()>);

impl Unsend {
    fn log(&self) {
        eprintln!(
            "ptr: 0x{:x}, thread: {:?}",
            Rc::as_ptr(&self.0) as usize,
            std::thread::current()
        );
    }
}

impl<T> Hotplug<T> for Unsend
where
    T: UsbContext,
{
    fn device_arrived(&mut self, _: Device<T>) {
        self.log()
    }

    fn device_left(&mut self, _: Device<T>) {
        self.log()
    }
}

fn main() -> Result<(), Error> {
    let foo = Unsend::default();
    foo.log();

    /*
    // Fails to compile because Unsend is not Send.
    std::thread::spawn(move || {
        drop(foo);
    });
    */

    let context = GlobalContext::default();
    let reg = context
        .register_callback(None, None, None, Box::new(foo))
        .unwrap();

    let handler = std::thread::spawn(move || loop {
        context.handle_events(None).ok();
    });

    handler.join().unwrap();
    context.unregister_callback(reg);
    Ok(())
}
```

When (un)plugging a device, it prints (note the different thread ids):

```
ptr: 0x55de6d819bb0, thread: Thread { id: ThreadId(1), name: Some("main") }
ptr: 0x55de6d819bb0, thread: Thread { id: ThreadId(2), name: None }
ptr: 0x55de6d819bb0, thread: Thread { id: ThreadId(2), name: None }
```

**Comment by a1ien** [comment]
Yes you correct it's unsound. I accept PR tomorrow.

**Comment by kevinmehall** [comment]
Allowing `Hotplug` to be `!Sync` and have`&mut self` parameters similarly needs to considered carefully. I think it's probably sound in its current form because libusb's internal `events_lock` prevents calling the handler multiple times concurrently. However, that's not explicitly guaranteed by the libusb documentation so could theoretically change in future versions of libusb. Also, rusb doesn't currently pass `LIBUSB_HOTPLUG_ENUMERATE`, but if it did, that looks like it would also allow calls to the callback without that lock held.

When reviewing this, I also found #54.
