### ISSUE TITLE
Praise: Partial static linking on macos just works!

### ISSUE THREAD

**Issue by raphaelcohn** [a1ien/rusb#91]
Wow! That's some success - it's a beast to get right. You might want to promote the vendoring feature a bit more. I'm all for it (and as a former Linux distro maintainer, all against pkg-config).

**Comment by a1ien** [comment]
No. I not promote vendoring feature by default. Also remember when you enable static link, `rusb` and whole you project licensed under LGPL as libusb.

**Comment by raphaelcohn** [comment]
I didn't mean by default, just to make it a bit more obvious.

**Comment by timfish** [comment]
I've been doing some testing on Windows and found that without vcpkg installed, `libusb1-sys` automatically falls back to static linking. Looking at `libusb1-sys/build.rs`, in any cases where `libusb` cannot be found vendoring is already the default.

This provides a great developer experience but also means that vendoring occurs when you might not expect it. I don't think this behaviour should be changed but it's something to be aware of!

> remember when you enable static link, `rusb` and whole you project licensed under LGPL as libusb.

Derivative works are not automatically LGPL when statically linking because there is an exception in LGPL v2.1:

>   6. As an exception to the Sections above, you may also combine or
link a "work that uses the Library" with the Library to produce a
work containing portions of the Library, and distribute that work
under terms of your choice, provided that the terms permit
modification of the work for the customer's own use and reverse
engineering for debugging such modifications.

If you provide a way for consumers to use their own copy of libusb with your derivative work then you can comply with LGPL and still distribute under terms of your choosing. 

This is usually achieved by supplying object files so consumers can build your app/library with their own libusb, however this is tricky to do with Rust due to no stable ABI, etc. 

My understanding is that you can comply with LPGL v2.1 while statically linking if you also supply a means to dynamically load libusb at runtime that overrides the statically linked code.

**Comment by timfish** [comment]
> Yes but it's no zero overhead method for doing this

Agreed. 

If I end up attempting this, I would only attempt to load the dynamic library if, for example a specific environment variable has been set. I would guess for most applications, it's highly unlikely anyone would ever actually use the dynamic feature. It's main use would be to satisfy LGPL 🤷‍♂️

**Comment by raphaelcohn** [comment]
I'm actually considering going down the road of writing my own implementation of the core parts of libusb in Rust partly because of the licensing. Being able to ship standalone binaries is very important to my use cases. It's not actually that hard, just tedious. It would also be an advantage to avoid a lot of unnecessary memory copies, and to provide my own memory allocators - that way I can guard against out-of-memory conditions if serving USB requests on a server, say. It would also be a way to make something have much richer error conditions (libusb's are pretty vague).

That said, I don;t have the time...

**Comment by timfish** [comment]
Writing a `libusb` replacement might be tedious, but testing it and confirming it's correctness is another whole level of pain. `libusb` has been tested with a decade worth of hardware devices. Unless you have access to a significant proportion of those devices it'll be a large team effort to get it to a similar level.
